name: GCToolKit Pre-release Notes

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '[maven-release-plugin]') != true

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        cache: 'maven'
        
    - name: Build with Maven
      run: ./mvnw -B verify --file pom.xml

    - name: Git-release
      run: |
        ./mvnw -B -pl :gctoolkit -Pjreleaser jreleaser:release
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
